package com.pezfa.inventario.models;
// Generated 22/04/2017 02:11:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cava generated by hbm2java
 */
public class Cava  implements java.io.Serializable {


     private int id;
     private Almacen almacen;
     private String nombre;
     private Set ubicacions = new HashSet(0);

    public Cava() {
    }

	
    public Cava(Almacen almacen, String nombre) {
        this.almacen = almacen;
        this.nombre = nombre;
    }
    public Cava(Almacen almacen, String nombre, Set ubicacions) {
       this.almacen = almacen;
       this.nombre = nombre;
       this.ubicacions = ubicacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUbicacions() {
        return this.ubicacions;
    }
    
    public void setUbicacions(Set ubicacions) {
        this.ubicacions = ubicacions;
    }




}


