package com.pezfa.inventario.models;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int id;
     private Proveedor proveedor;
     private Usuario usuario;
     private String orden;
     private Date fecha;
     private Date hora;
     private BigDecimal gasto;
     private Set compraEspecies = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int id, Proveedor proveedor, Usuario usuario, String orden) {
        this.id = id;
        this.proveedor = proveedor;
        this.usuario = usuario;
        this.orden = orden;
    }
    public Compra(int id, Proveedor proveedor, Usuario usuario, String orden, Date fecha, Date hora, BigDecimal gasto, Set compraEspecies) {
       this.id = id;
       this.proveedor = proveedor;
       this.usuario = usuario;
       this.orden = orden;
       this.fecha = fecha;
       this.hora = hora;
       this.gasto = gasto;
       this.compraEspecies = compraEspecies;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public BigDecimal getGasto() {
        return this.gasto;
    }
    
    public void setGasto(BigDecimal gasto) {
        this.gasto = gasto;
    }
    public Set getCompraEspecies() {
        return this.compraEspecies;
    }
    
    public void setCompraEspecies(Set compraEspecies) {
        this.compraEspecies = compraEspecies;
    }




}


