package com.pezfa.inventario.models;
// Generated 03/06/2017 11:52:53 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CompraInsumo generated by hbm2java
 */
public class CompraInsumo  implements java.io.Serializable {


     private int id;
     private Compra compra;
     private Insumo insumo;
     private double cantidad;
     private BigDecimal costo;

    public CompraInsumo() {
    }

	
    public CompraInsumo(int id, Compra compra, Insumo insumo, double cantidad) {
        this.id = id;
        this.compra = compra;
        this.insumo = insumo;
        this.cantidad = cantidad;
    }
    public CompraInsumo(int id, Compra compra, Insumo insumo, double cantidad, BigDecimal costo) {
       this.id = id;
       this.compra = compra;
       this.insumo = insumo;
       this.cantidad = cantidad;
       this.costo = costo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }




}


