package com.pezfa.inventario.models;


/**
 * DetalleProduccion generated by hbm2java
 */
public class DetalleProduccion  implements java.io.Serializable {


     private int id;
     private Produccion produccion;
     private Unidad unidad;

    public DetalleProduccion() {
    }

    public DetalleProduccion(int id, Produccion produccion, Unidad unidad) {
       this.id = id;
       this.produccion = produccion;
       this.unidad = unidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produccion getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Produccion produccion) {
        this.produccion = produccion;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }




}


