package com.pezfa.inventario.models;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produccion generated by hbm2java
 */
public class Produccion  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Date fecha;
     private BigDecimal inversion;
     private Set terminados = new HashSet(0);
     private Set detalleProduccions = new HashSet(0);

    public Produccion() {
    }

	
    public Produccion(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public Produccion(int id, String descripcion, Date fecha, BigDecimal inversion, Set terminados, Set detalleProduccions) {
       this.id = id;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.inversion = inversion;
       this.terminados = terminados;
       this.detalleProduccions = detalleProduccions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getInversion() {
        return this.inversion;
    }
    
    public void setInversion(BigDecimal inversion) {
        this.inversion = inversion;
    }
    public Set getTerminados() {
        return this.terminados;
    }
    
    public void setTerminados(Set terminados) {
        this.terminados = terminados;
    }
    public Set getDetalleProduccions() {
        return this.detalleProduccions;
    }
    
    public void setDetalleProduccions(Set detalleProduccions) {
        this.detalleProduccions = detalleProduccions;
    }




}


