package com.pezfa.inventario.models;

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int id;
     private String rif;
     private String nombre;
     private String direccion;
     private String telefono;
     private String correo;
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int id, String rif, String nombre, String direccion) {
        this.id = id;
        this.rif = rif;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Proveedor(int id, String rif, String nombre, String direccion, String telefono, String correo, Set compras) {
       this.id = id;
       this.rif = rif;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.compras = compras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRif() {
        return this.rif;
    }
    
    public void setRif(String rif) {
        this.rif = rif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


