package com.pezfa.inventario.models;

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Terminado generated by hbm2java
 */
public class Terminado extends ProductoSalida  implements java.io.Serializable {


     private Produccion produccion;
     private Producto producto;
     private Date vencimiento;
     private String lote;
     private boolean estado;
     private Set ventaTerminados = new HashSet(0);

    public Terminado() {
    }

	
    public Terminado(Produccion produccion, Producto producto, Date vencimiento, String lote) {
        this.produccion = produccion;
        this.producto = producto;
        this.vencimiento = vencimiento;
        this.lote = lote;
    }

    public Terminado(Produccion produccion, Producto producto, Date vencimiento, String lote, boolean estado)
    {
        this.produccion = produccion;
        this.producto = producto;
        this.vencimiento = vencimiento;
        this.lote = lote;
        this.estado = estado;
    }

    public boolean isEstado()
    {
        return estado;
    }

    public void setEstado(boolean estado)
    {
        this.estado = estado;
    }
  
    public Produccion getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Produccion produccion) {
        this.produccion = produccion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Set getVentaTerminados() {
        return this.ventaTerminados;
    }
    
    public void setVentaTerminados(Set ventaTerminados) {
        this.ventaTerminados = ventaTerminados;
    }

    @Override
    public int hashCode()
    {
        int hash = 5;
        hash = 13 * hash + Objects.hashCode(this.producto);
        return hash;
    }

    @Override
    public boolean equals(Object obj)
    {
        if (this == obj)
        {
            return true;
        }
        if (obj == null)
        {
            return false;
        }
        if (getClass() != obj.getClass())
        {
            return false;
        }
        final Terminado other = (Terminado) obj;
        if (!Objects.equals(this.producto, other.producto))
        {
            return false;
        }
        return true;
    }
    
    


}


