package com.pezfa.inventario.models;
// Generated 28-ene-2017 17:44:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Terminado generated by hbm2java
 */
public class Terminado  implements java.io.Serializable {


     private int id;
     private Produccion produccion;
     private Producto producto;
     private Date vencimiento;
     private String lote;
     private Set ventaTerminados = new HashSet(0);

    public Terminado() {
    }

	
    public Terminado(int id, Produccion produccion, Producto producto, Date vencimiento, String lote) {
        this.id = id;
        this.produccion = produccion;
        this.producto = producto;
        this.vencimiento = vencimiento;
        this.lote = lote;
    }
    public Terminado(int id, Produccion produccion, Producto producto, Date vencimiento, String lote, Set ventaTerminados) {
       this.id = id;
       this.produccion = produccion;
       this.producto = producto;
       this.vencimiento = vencimiento;
       this.lote = lote;
       this.ventaTerminados = ventaTerminados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produccion getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Produccion produccion) {
        this.produccion = produccion;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Set getVentaTerminados() {
        return this.ventaTerminados;
    }
    
    public void setVentaTerminados(Set ventaTerminados) {
        this.ventaTerminados = ventaTerminados;
    }




}


