package com.pezfa.inventario.models;

/**
 * VentaUnidad generated by hbm2java
 */
public class VentaUnidad extends VentaDetalle implements java.io.Serializable {


     private int id;
     private Unidad unidad;

    public VentaUnidad() {
    }

    public VentaUnidad(int id, Unidad unidad ) {
       this.id = id;
       this.unidad = unidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
 
}


