package com.pezfa.inventario.models;
// Generated 28-ene-2017 17:44:34 by Hibernate Tools 4.3.1



/**
 * VentaTerminado generated by hbm2java
 */
public class VentaTerminado  implements java.io.Serializable {


     private int id;
     private Terminado terminado;
     private Venta venta;

    public VentaTerminado() {
    }

    public VentaTerminado(int id, Terminado terminado, Venta venta) {
       this.id = id;
       this.terminado = terminado;
       this.venta = venta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Terminado getTerminado() {
        return this.terminado;
    }
    
    public void setTerminado(Terminado terminado) {
        this.terminado = terminado;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


