package com.pezfa.inventario.models;
/**
 * VentaTerminado generated by hbm2java
 */
public class VentaTerminado  extends VentaDetalle implements java.io.Serializable {


     private int id;
     private Terminado terminado;

    public VentaTerminado() {
    }

    public VentaTerminado(int id, Terminado terminado) {
       this.id = id;
       this.terminado = terminado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Terminado getTerminado() {
        return this.terminado;
    }
    
    public void setTerminado(Terminado terminado) {
        this.terminado = terminado;
    }
}


