package com.pezfa.inventario.models;
// Generated 22/04/2017 02:11:01 PM by Hibernate Tools 4.3.1



/**
 * VentaEspecie generated by hbm2java
 */
public class VentaEspecie extends VentaDetalle  implements java.io.Serializable {


     private int id;
     private Ubicacion ubicacion;

    public VentaEspecie() {
    }

   
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    
}


